/****************************************************************************
 * vendor/bouffalolab/boards/bl616cl/bl616cldg/scripts/ld.script
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

OUTPUT_ARCH(riscv)
ENTRY(__start)

MEMORY
{
  flash (rx)  : ORIGIN = 0x80000000, LENGTH = 2M
  ram   (rwx) : ORIGIN = 0x20fc0000, LENGTH = 384K
}

SECTIONS
{
  .text : {
    _stext = ABSOLUTE(.);
    KEEP(*(.text.entry))
    *(.text .text.*)
    *(.rodata .rodata.*)
    *(.srodata .srodata.*)
    *(.gnu.linkonce.t.*)
    *(.gnu.linkonce.r.*)
    . = ALIGN(4);
    _etext = ABSOLUTE(.);
  } > flash

  .init_section : {
    _sinit = ABSOLUTE(.);
    KEEP(*(SORT_BY_INIT_PRIORITY(.init_array.*)))
    KEEP(*(.init_array))
    _einit = ABSOLUTE(.);
  } > flash

  _eronly = LOADADDR(.data);

  .data : AT(_eronly) {
    _sdata = ABSOLUTE(.);
    __global_pointer$ = . + 0x800;
    *(.data .data.*)
    *(.sdata .sdata.*)
    *(.gnu.linkonce.d.*)
    . = ALIGN(4);
    _edata = ABSOLUTE(.);
  } > ram

  .bss (NOLOAD) : {
    _sbss = ABSOLUTE(.);
    *(.bss .bss.*)
    *(.sbss .sbss.*)
    *(COMMON)
    . = ALIGN(16);
    _ebss = ABSOLUTE(.);
  } > ram

  . = ALIGN(16);
  __HeapBase = ABSOLUTE(.);
  __IdleStackSize = 2048;
  . = ORIGIN(ram) + LENGTH(ram) - __IdleStackSize;
  __HeapLimit = ABSOLUTE(.);
  . = ALIGN(16);
  __StackBase = ABSOLUTE(.);
  . += __IdleStackSize;
  __StackTop = ABSOLUTE(.);

  /DISCARD/ : {
    *(.note.GNU-stack)
    *(.riscv.attributes)
  }

  .comment 0 : { *(.comment) }
  .debug_abbrev 0 : { *(.debug_abbrev) }
  .debug_info 0 : { *(.debug_info) }
  .debug_line 0 : { *(.debug_line) }
  .debug_str 0 : { *(.debug_str) }
}
