/****************************************************************************
 * vendor/bouffalolab/boards/bl616cl/bl616cldg/scripts/ld.script
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#include <nuttx/config.h>

OUTPUT_ARCH(riscv)
ENTRY(__start)

MEMORY
{
  flash (rx)  : ORIGIN = 0x80000000, LENGTH = 2M
  ram   (rwx) : ORIGIN = 0x20fc0000, LENGTH = 384K
}

SECTIONS
{
  .text : {
    _stext = ABSOLUTE(.);
    KEEP(*(.text.entry))
    *(.text .text.*)
    *(.rodata .rodata.*)
    *(.srodata .srodata.*)
    *(.gnu.linkonce.t.*)
    *(.gnu.linkonce.r.*)
    . = ALIGN(4);
    _etext = ABSOLUTE(.);
  } > flash

  .init_section : {
    _sinit = ABSOLUTE(.);
    KEEP(*(SORT_BY_INIT_PRIORITY(.init_array.*)))
    KEEP(*(.init_array))
    _einit = ABSOLUTE(.);
  } > flash

  .copy.table : {
    __mem_copy_sections = ABSOLUTE(.);
    LONG(ADDR(.ram_code));
    LONG(ADDR(.ram_code) + SIZEOF(.ram_code));
    LONG(LOADADDR(.ram_code));
    LONG(ADDR(.ram_rodata));
    LONG(ADDR(.ram_rodata) + SIZEOF(.ram_rodata));
    LONG(LOADADDR(.ram_rodata));
    LONG(ADDR(.data));
    LONG(ADDR(.data) + SIZEOF(.data));
    LONG(LOADADDR(.data));
    LONG(0xffffffff);
    LONG(0xffffffff);
    LONG(0xffffffff);
  } > flash

  .zero.table : {
    __mem_setz_sections = ABSOLUTE(.);
    LONG(ADDR(.bss));
    LONG(ADDR(.bss) + SIZEOF(.bss));
    LONG(0xffffffff);
    LONG(0xffffffff);
  } > flash

  __LD_CONFIG_EM_SEL = 0;

  .ram_code : {
    . = ALIGN(4);
    *(.tcm_code*)
    *(.sclock_rlt_code*)
    . = ALIGN(4);
  } > ram AT > flash

  .ram_rodata : {
    . = ALIGN(4);
    *(.tcm_const*)
    *(.sclock_rlt_const*)
    . = ALIGN(4);
  } > ram AT > flash

  .data : {
    _sdata = ABSOLUTE(.);
    __global_pointer$ = . + 0x800;
    *(.data .data.*)
    *(.sdata .sdata.*)
    *(.tcm_data*)
    *(.nocache_ram)
    *(.gnu.linkonce.d.*)
    . = ALIGN(4);
    _edata = ABSOLUTE(.);
  } > ram AT > flash

  .noinit (NOLOAD) : {
    *(.noinit .noinit.*)
    *(.nocache_noinit_ram)
    *(.noncacheable)
    . = ALIGN(16);
  } > ram

  .bss (NOLOAD) : {
    _sbss = ABSOLUTE(.);
    *(.bss .bss.*)
    *(.sbss .sbss.*)
    *(COMMON)
    . = ALIGN(16);
    _ebss = ABSOLUTE(.);
  } > ram

  . = ALIGN(16);
  __StackBase = ABSOLUTE(.);
  . += CONFIG_IDLETHREAD_STACKSIZE;
  __StackTop = ABSOLUTE(.);
  __HeapBase = ABSOLUTE(.);
  __HeapLimit = ORIGIN(ram) + LENGTH(ram);

  ASSERT(__HeapBase < __HeapLimit, "BL616CL RAM overflow")

  /DISCARD/ : {
    *(.note.GNU-stack)
    *(.riscv.attributes)
  }

  .comment 0 : { *(.comment) }
  .debug_abbrev 0 : { *(.debug_abbrev) }
  .debug_info 0 : { *(.debug_info) }
  .debug_line 0 : { *(.debug_line) }
  .debug_str 0 : { *(.debug_str) }
}
