[cfg]
# 0: no erase, 1: programmed section erase, 2: chip erase
erase = 1
# First value is skip address, second value is skip length.
skip_mode = 0x0, 0x0
# 0: normal boot2, 1: ISP boot2
boot2_isp_mode = 0

[boot2]
filedir = ./boot2_bl616cl_isp_release_v8.2.1.bin
address = 0x000000

[partition]
filedir = ./partition.bin
address = 0xE000

[partition_b]
filedir = ./partition.bin
address = 0xF000

[FW]
filedir = ./nuttx.bin
address = @partition
